// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNu1jB-jnRSutr606RpF6z5m56x8ptZxw',
    appId: '1:1015489538808:web:fba17f6581729984e9290d',
    messagingSenderId: '1015489538808',
    projectId: 'snake-identifier-app',
    authDomain: 'snake-identifier-app.firebaseapp.com',
    storageBucket: 'snake-identifier-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBqPAO7AU-knHw-0g5V5InxLlPMYTbzY4',
    appId: '1:1015489538808:android:303ff56fccafe815e9290d',
    messagingSenderId: '1015489538808',
    projectId: 'snake-identifier-app',
    storageBucket: 'snake-identifier-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQRewDNA9vwXXsJPFQK6I7Njc_dOr2ZpQ',
    appId: '1:1015489538808:ios:f29f800cfc733116e9290d',
    messagingSenderId: '1015489538808',
    projectId: 'snake-identifier-app',
    storageBucket: 'snake-identifier-app.appspot.com',
    iosClientId: '1015489538808-9fceujrouv54jkubhbmr2ngdahitobrr.apps.googleusercontent.com',
    iosBundleId: 'com.example.snakeapp',
  );
}
